### ISSUE TITLE
Howto: Upgrade to 0.5.0

### ISSUE THREAD

**Issue by mpharding** [abajwa-hw/ambari-nifi-service#4]
Hi,

I've installed NiFi as a service through Ambari on my cluster which works great but I want to upgrade to the latest release 0.5.0. What steps do I need to take in order to do this ?

Thanks,
Mike

**Comment by abajwa-hw** [comment]
Currently the Ambari service does not support upgrading. Easiest way would be to just remove the old one (https://github.com/abajwa-hw/ambari-nifi-service#remove-service) and re-install

**Comment by mpharding** [comment]
But if I re-install ambari nifi-service through ambari will it not still use an older version of nifi (0.4.1) ?

Would it be as simple as changing the following URL to point to the latest build?

e.g. change: 
#official HDF 1.1.1 package (nifi 0.4.1)
snapshot_package='http://public-repo-1.hortonworks.com/HDF/1.1.1.0/nifi-1.1.1.0-12-bin.zip' 

to:

snapshot_package='http://apache.mirror.anlx.net/nifi/0.5.0/nifi-0.5.0-bin.tar.gz'

**Comment by abajwa-hw** [comment]
Good point. These were the changes made to update from HDF 1.1.0 to 1.1.1. 
https://github.com/abajwa-hw/ambari-nifi-service/commit/ee61171efe79c82ef21576ed49212d3a0bb7d25a

Similar should work for you

**Comment by abajwa-hw** [comment]
@hardboy111: just updated the service to install HDF 1.1.2.0 (nifi 0.5.1):
https://github.com/abajwa-hw/ambari-nifi-service/commit/5c6961deaffbd689b55b4e14b9dd7ab9d467bc24

**Comment by mpharding** [comment]
thank you - il close this now.
