### ISSUE TITLE
Upgrade to HDF 1.2.0.1 (nifi 0.6.0)

### ISSUE THREAD

**Issue by nickraptis** [abajwa-hw/ambari-nifi-service#9]
1.2.0.1 dropped and it has some useful bugfixes, while staying at the same version of nifi.
http://docs.hortonworks.com/HDPDocuments/HDF1/HDF-1.2.0.1/bk_HDF_RelNotes/content/ch_hdf_relnotes.html
Since there are no configuration changes I see, it should be very straightforward to update the service to the new version.

**Comment by ZacBlanco** [comment]
@nickraptis I made a pull request to update it

**Comment by ZacBlanco** [comment]
@nickraptis Pull request was merged in. Repo now supports the latest version of HDF

**Comment by nickraptis** [comment]
I was just now going to make a pull request of my own but you beat me to it.
We ended up with exactly the same changes so I'm confident we didn't overlook something ;)
Thank you so much for your work and promptness.
